# Generated by Django 4.1.7 on 2023-03-18 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
    ]
