# Generated by Django 4.1.7 on 2023-03-11 10:57

from django.db import migrations
from django.core.management import call_command


def func(apps, schema_editor):
    call_command("loaddata", "data_fixture.json")


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0002_initial"),
        ("sessions", "0001_initial"),
        ("django_q", "0014_schedule_cluster"),
    ]

    operations = [migrations.RunPython(func)]
