# Generated by Django 4.1.7 on 2023-03-18 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_telegramchat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramchat",
            old_name="chat_id",
            new_name="chat_user_id",
        ),
    ]
